from flask import Blueprint
from .auth import auth_bp
from .facilities import fac_bp
from .info import info_bp
from .monitors import monitor_bp
from .users import usr_bp
from .vehicles import veh_bp
from .visitors import vis_bp
from .warehouses import warehouse_bp
from .warnings import warn_bp
