###根据search的字段获取符合条件的所有用户
GET http://127.0.0.1:5000/users/
Content-Type: application/json

{
  "type": "",
  "name": "",
  "page_num": 2,
  "per_page": 5
}

###批量删除用户信息
DELETE http://127.0.0.1:5000/users/
Content-Type: application/json

{
  "list_to_del": [1,2]
}


###新增一个用户信息
POST http://127.0.0.1:5000/users/
Content-Type: application/json

{
  "realname" : "1",
  "password": "1",
  "type": "admin",
  "department": "1",
  "isused": true,
  "createtime": "",
  "isfaceused": true
}

###删除一个用户信息
DELETE http://127.0.0.1:5000/users/2

###编辑一个用户
PUT http://127.0.0.1:5000/users/1
Content-Type: application/json

{
  "realname" : "realname1",
  "password": "password1",
  "type": "a",
  "department": "2",
  "isused": true,
  "createtime": "2023-2-6 15:03:01",
  "isfaceused": true
}